server:
  port: 8000
  max-http-header-size: 10240
  servlet:
    context-path: /api
  tomcat:
    uri-encoding: UTF-8
    
logging:
    level:
      com.ysx.modules.*.mapper: DEBUG
      
spring:
  application:
    name: xmlx
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource 
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/project_exercise?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: juan940423
#    druid:
#      initial-size: 10
#      max-active: 500
#      min-idle: 10
#      max-wait: 60000
#      pool-prepared-statements: true
#      max-pool-prepared-statement-per-connection-size: 20
#      validation-query: SELECT 'x'
#      test-on-borrow: false
#      test-on-return: false
#      test-while-idle: true
#      time-between-eviction-runs-millis: 60000
#      min-evictable-idle-time-millis: 300000
#      filters: stat,wall
  # 格式化时间
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  
  thymeleaf:
    #缓冲的配置
    cache: false
    check-template: true
    check-template-location: true
    #开启MVC thymeleaf 视图解析
    enabled: true
    encoding: utf-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
    
  security:
    basic:
      enabled: false
#    user:
#      name: admin
#      password: admin
#    filter:
#      excludePathPatterns: >
#       /test/**
#  thymeleaf:
#    cache: false #关闭缓存
#    mode: HTML5 #设置模板类型
#    encoding: utf-8  #设置编码
                
            
mybatis-plus:
  #xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）  
  mapper-locations: classpath*:/mappers/*.xml
  #MyBaits 别名包扫描路径，通过该属性可以给包中的类注册别名
  type-aliases-package: com.ysx.*.domain
#  global-config:
#    # 逻辑删除配置
#    db-config:
#      # 删除前
#      logic-not-delete-value: 1
#      # 删除后
#      logic-delete-value: 0

pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: false
  params: count=countSql

jwt:
  secret: secret
  expiration: 7200000
  token: Authorization
 